### ISSUE TITLE
missing "auto-reload-config" in "new" tab when creating deployment

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#103]
in design doc
![image](https://user-images.githubusercontent.com/47511655/59398044-507bb580-8dc1-11e9-96a7-561a42610e7b.png)

in frontend
![image](https://user-images.githubusercontent.com/47511655/59398065-5d000e00-8dc1-11e9-939b-ecc8cf0407b8.png)

**Comment by gsmlg** [comment]
auto-reload-config is in tab of AdvancedOptions

**Comment by tanxu-zdns** [comment]
yes , in the advancedoptions
