### ISSUE TITLE
missing "network detail" in network page

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#114]
in the frond-end
<img width="822" alt="image" src="https://user-images.githubusercontent.com/47511655/59650863-260f6b00-91ba-11e9-958f-52098c1347c8.png">

in the design doc
<img width="762" alt="image" src="https://user-images.githubusercontent.com/47511655/59650882-3a536800-91ba-11e9-873a-7a9b8a0c5945.png">

**Comment by gsmlg** [comment]
There is no implementation for these data.

**Comment by gsmlg** [comment]
这个现在是集群管理中的配置，现在没有展示

**Comment by gsmlg** [comment]
产品确认，不再展示
