### ISSUE TITLE
resource doc can't fully describe the response of each method.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#13]
doc contains GET, POST, PUT, DELETE method, but only contains one response 'resourceFields', so we can't distinguish the response 'resourceFields' belongs to which method.

for example, GET and POST have the different response.

in the daemonset doc, response 'resourceFields' contains 'status'.  
but there is no 'status' when creating (post) a daemonset. 
After creating, 'status' should be found in the response (GET).

**Comment by zdnsjoe** [comment]
todo
