### ISSUE TITLE
resource fields in doc 'jobs.json' contains 'int' and 'int32' which are not consistent with other docs

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#14]
for example:
in jobs.json contains

    "resourceFields": {
        "name": {"type": "string"},
        "parallelism": {"type": "**int32**"},
        "completions": {"type": "**int32**"},
        "backoffLimit": {"type": "**int32**"},
        "nodeName": {"type": "string"},
        "restartPolicy": {"type": "enum", "validValues": ["OnFailure", "Never"]},
        "containers": {"type": "array", "elemType": "container"},
        "status": {"type": "jobStatus"}
    }
and 
  "deploymentPort": {
            "name" : {"type": "string"},
            "port" : {"type": "**int**"},
            "protocol": {"type": "enum", "validValues": ["tcp", "udp"]}
        }

but in other docs only contains type "int".

**Comment by zdnsjoe** [comment]
todo
