### ISSUE TITLE
error should return if user try to create the same type storagecluster

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#141]
1. create a ceph storage,
2. create another ceph storage,

the following occurs:
ceph storage created two times.

builder$ kubectl -n zcloud get cluster
NAME                   AGE   STATE
storagecluster-ceph    1m
storagecluster-ceph1   57s
storagecluster-ceph2   53s
storagecluster-ceph3   49s

expected behavior:
returns errors to notice user that the same type storage could only create once.

**Comment by yuchunyun** [comment]
If you create the storagecluster from the foreground, there will be repeated prompts
