### ISSUE TITLE
pvc will keep "pending" after reducing the storage node

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#143]
1. create storage with 2 node with lvm,
2. delete a node,
3. create a deployment with lvm,

the following occurs:
pvc keep "pending".

Normal | Provisioning | External provisioner is provisioning volume for claim "default/vol1-state-lvm-0" | 3 minutes ago
-- | -- | -- | --
Warning | ProvisioningFailed | failed to provision volume with StorageClass "lvm": failed to get capabilities: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /csi/csi.sock: connect: no such file or directory" | 3 minutes ago
Normal | ExternalProvisioning | waiting for a volume to be created, either by external provisioner "csi-lvmplugin" or manually created by system administrator | a minute ago

**Comment by yuchunyun** [comment]
cause： The csi-provisioner dependency socket has been removed  by csi-lvmplugin
solution: Remove nodeselector from DaemonSet csi-lvmplugin
