### ISSUE TITLE
no prompt when user login with wrong username or password

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#153]
1. go to login page,
2. login with wrong user or password,

the following occurs:
no prompt come out.

<img width="1435" alt="noprompt" src="https://user-images.githubusercontent.com/47511655/61931541-734ddc00-afb3-11e9-9ff6-3ef537aaead0.png">

**Comment by gsmlg** [comment]
No server error has been returned

**Comment by tanxu-zdns** [comment]
@zdnsjoe  please check

**Comment by tanxu-zdns** [comment]
@thesinglecloud please check

**Comment by gsmlg** [comment]
fixed on master
use image zdnscloud/singlecloud:v0.1-420-gd250b54
