### ISSUE TITLE
missing "Gi" unit in memery and storage  when creating userquota

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#156]
![missingGiquota](https://user-images.githubusercontent.com/47511655/62021210-b3ea6700-b1f8-11e9-88d7-b0d325f0b9b7.png)

**Comment by tanxu-zdns** [comment]
still present

**Comment by gsmlg** [comment]
fixed on master
use image zdnscloud/singlecloud:v0.1-420-gd250b54
