### ISSUE TITLE
cup.limit and memery.limit is needed when creating resource with resourcequota

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#157]
1. normal user apply a userquota,
2. admin pass the userquota,
3. normal user create a deployment,

the following occurs:
error returns
Error creating: pods "quota1-795bf8f5cb-fqzzh" is forbidden: failed quota: quota-test1: must specify limits.cpu,limits.memory

**Comment by zdnsjoe** [comment]
fix on branch issue157

**Comment by tanxu-zdns** [comment]
still present, only one pod can be created. 

if continue creating, event error occurs:
(combined from similar events): Error creating: pods "sdfsfsdfs-6bdd77fd89-lwz8b" is forbidden: exceeded quota: quota-test-0-11, requested: limits.cpu=5,limits.memory=5Gi, used: limits.cpu=5,limits.memory=5Gi, limited: limits.cpu=5,limits.memory=5Gi

**Comment by zdnsjoe** [comment]
a temporary plan, just limit storage, and will limit cpu and memory in the future

**Comment by zdnsjoe** [comment]
fix on update-user-quota
