### ISSUE TITLE
extra "Gi" displays in the userquota list page and detail page

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#158]
<img width="1919" alt="extraGi" src="https://user-images.githubusercontent.com/47511655/62029882-56651300-b216-11e9-9203-56aa35aeba6e.png">
<img width="1615" alt="extragide" src="https://user-images.githubusercontent.com/47511655/62029928-6da40080-b216-11e9-8605-f64af6fa2666.png">

**Comment by tanxu-zdns** [comment]
still present on detail page

**Comment by gsmlg** [comment]
fixed on master
use image zdnscloud/singlecloud:v0.1-420-gd250b54
