### ISSUE TITLE
the sorting of userquota keep changing when login as normal user

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#164]
please refer to this video

[namekeepflikering.mov.zip](https://github.com/zdnscloud/singlecloud/files/3445478/namekeepflikering.mov.zip)

**Comment by tanxu-zdns** [comment]
![20190730-144525](https://user-images.githubusercontent.com/47511655/62106784-af957b00-b2d8-11e9-9549-544d6d501adc.png)

**Comment by gsmlg** [comment]
@zdnsjoe 
Userquota Data collection should keep in order.
