### ISSUE TITLE
action button "remove" and "create" should be removed when login as normal user

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#166]
1. normal user apply a namespace,
2. admin create the namespace,
3. normal user try to delete the namespace and create new namespace

the following occurs:
errors retruns.

expected behavior:
remove the button "remove" and "create".
![delcre](https://user-images.githubusercontent.com/47511655/62107997-7ad6f300-b2db-11e9-9bf6-469a14ca1dc9.png)
![createname](https://user-images.githubusercontent.com/47511655/62108003-80ccd400-b2db-11e9-84f2-a1d74a5eef12.png)

**Comment by gsmlg** [comment]
Next version will remove namespace page when login as normal user, so do not fix this.
