### ISSUE TITLE
[random] coredns in pending status when creating cluster

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#177]
![corep](https://user-images.githubusercontent.com/47511655/62517352-d7955900-b859-11e9-985a-5631b23621ae.png)

![corepending](https://user-images.githubusercontent.com/47511655/62517306-b896c700-b859-11e9-8744-32f638fcf1d3.png)

**Comment by hiwyw** [comment]
this is a bug of kubernetes, plan update kubernetes version to v1.13.9 to resolve ,and the bug issue is https://github.com/kubernetes/kubernetes/pull/72558
