### ISSUE TITLE
cluster list api return slow when apiserver hang

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#179]
1. create a health cluster,
2. add a broken node (e.g. input wrong ip),
3. try to delete the broken node,

the following occurs:
there is no responding when deleting the node

note:
the cluster is in unavailable status

**Comment by hiwyw** [comment]
has fixed in branch node-manager when an cluster is unready will retrun  immediately，but api will wait timeout(one cluster will wait 1min30s) when an running cluster's apiserver is no responding(tcp port 6443 is open) because singlecloud need to get some cluster info from apiserver

**Comment by hiwyw** [comment]
suggest create another issue or change this issue title: cluster list api return slow when apiserver hang
