### ISSUE TITLE
it's better to provide logs when cluster in unavailable status

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#180]
![log](https://user-images.githubusercontent.com/47511655/62524202-c94e3980-b867-11e9-9bd7-1e38eb77b895.png)

**Comment by jlccwss** [comment]
设计时，我们没有做日志保存功能，功能需要设计，最迟下一版解决

**Comment by hiwyw** [comment]
v2.0已支持
