### ISSUE TITLE
missing "deleting storage node" function in front-end

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#187]
1. add a ceph storage with two node storage,
2. try to remove one of them,

the following occurs:
no deleting function found in the UI.

![missingfunction](https://user-images.githubusercontent.com/47511655/63005522-52402300-beaf-11e9-8f9c-517258cfbfdc.png)

**Comment by gsmlg** [comment]
取消选中即为删除

**Comment by tanxu-zdns** [comment]
前端的主机名下面是空的(后端有数据), 无法取消选中

**Comment by gsmlg** [comment]
没有选项是因为没有blockdevices了

**Comment by yuchunyun** [comment]
使用 apis/zcloud.cn/v1/clusters/local/storageclusters/lvm-cluster 返回中config字段，表明当前存储使用的节点

**Comment by gsmlg** [comment]
已解决，前端分支：
fix-bug189
