### ISSUE TITLE
missing bad status if some of the storage node go wrong

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#189]
in the ui
![image](https://user-images.githubusercontent.com/47511655/63080663-436f7400-bf74-11e9-9ad1-45293a949b90.png)

in the design doc
![image](https://user-images.githubusercontent.com/47511655/63080705-584c0780-bf74-11e9-994b-ddc402ce8704.png)

**Comment by gsmlg** [comment]
已修复，前端分支：
fix-bug189
