### ISSUE TITLE
nothing returns when getting storage cluster if delete all the storage host

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#190]
builder$ kubectl get cluster -o wide
NAME   AGE   STATE
ceph   3h    Running

but getting http://10.0.0.30:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclusters will get stuck and returns nothing.

**Comment by yuchunyun** [comment]
singlecloud/storagecluster-node-stat not allow to delete all storage host
