### ISSUE TITLE
singlecloud-ui helm 分支 make docker 报错

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#193]
docker build -t zdnscloud/singlecloud-ui:`git branch | sed -n '/\* /s///p'` --build-arg version=`git describe --tags` --build-arg buildtime=`date +%FT%T%z` --build-arg branch=`git branch | sed -n '/\* /s///p'` .
Sending build context to Docker daemon  32.02MB
Step 1/12 : FROM node:12-alpine as uibuild
 ---> 8fd54fb9eb5c
Step 2/12 : RUN apk --no-cache add make
 ---> Using cache
 ---> 9aa8db494f94
Step 3/12 : COPY . /singlecloud-ui
 ---> cc0e83c5a21a
Step 4/12 : RUN cd /singlecloud-ui && make build
 ---> Running in 62efb1e6dc19
yarn && npm run bootstrap
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @gsmlg/com@1.0.0-beta.0" has unmet peer dependency "react@^16.8.0".
warning " > @gsmlg/com@1.0.0-beta.0" has unmet peer dependency "react-dom@^16.8.0".
warning " > @gsmlg/utils@1.0.0-beta.0" has unmet peer dependency "react@^16.8.0".
warning " > @gsmlg/utils@1.0.0-beta.0" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @gsmlg/com > @material-ui/system@4.3.3" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @gsmlg/com > @material-ui/system@4.3.3" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @gsmlg/com > @material-ui/utils@4.3.0" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @gsmlg/com > @material-ui/utils@4.3.0" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @gsmlg/com > react-event-listener@0.6.6" has unmet peer dependency "react@^16.3.0".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @singlecloud/ui > react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
warning "workspace-aggregator-9a03625a-cf38-4af0-afd6-e9ad0a28f0bf > @singlecloud/ui > jest-styled-components@7.0.0-beta.1" has incorrect peer dependency "styled-components@>= 5 || >= 5.0.0-alpha.0 || >= 5.0.0-beta.0".
[4/4] Building fresh packages...
error /singlecloud-ui/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /singlecloud-ui/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linuxmusl-x64.tar.gz
ERR! sharp Please delete /root/.npm/_libvips/libvips-8.7.4-linuxmusl-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.8.0 | linux | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/singlecloud-ui/node_modules/node-gyp/lib/find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (/singlecloud-ui/node_modules/node-gyp/lib/find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/singlecloud-ui/node_modules/node-gyp/lib/find-python.js:175:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/singlecloud-ui/node_modules/node-gyp/lib/find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
gyp ERR! System Linux 4.4.0-137-generic
gyp ERR! command "/usr/local/bin/node" "/singlecloud-ui/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /singlecloud-ui/node_modules/sharp
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:15: bootstrap] Error 1
The command '/bin/sh -c cd /singlecloud-ui && make build' returned a non-zero code: 2
Makefile:21: recipe for target 'build-image' failed
make: *** [build-image] Error 2

**Comment by gsmlg** [comment]
网络问题，有些依赖下载失败了
