### ISSUE TITLE
reatio data cpu, memory, pod, storage in response of nodes are incorrect

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#2]
get http://sc1.sc1.10.0.0.32.xip.io/zcloud.cn/v1/clusters/local/nodes/worker1
response
{
    "id": "worker1",
    "links": {
        "collection": "http://sc1.sc1.10.0.0.32.xip.io/zcloud.cn/v1/clusters/local/nodes",
        "self": "http://sc1.sc1.10.0.0.32.xip.io/zcloud.cn/v1/clusters/local/nodes/worker1"
    },
    "creationTimestamp": "2019-02-13T05:46:31Z",
    "name": "worker1",
    "address": "10.0.0.32",
    "role": "worker",
    "labels": {
        "beta.kubernetes.io/arch": "amd64",
        "beta.kubernetes.io/fluentd-ds-ready": "true",
        "beta.kubernetes.io/os": "linux",
        "kubernetes.io/hostname": "worker1",
        "node-role.kubernetes.io/worker": "true"
    },
    "annotations": {
        "flannel.alpha.coreos.com/backend-data": "null",
        "flannel.alpha.coreos.com/backend-type": "host-gw",
        "flannel.alpha.coreos.com/kube-subnet-manager": "true",
        "flannel.alpha.coreos.com/public-ip": "10.0.0.32",
        "node.alpha.kubernetes.io/ttl": "0",
        "rke.cattle.io/external-ip": "10.0.0.32",
        "rke.cattle.io/internal-ip": "10.0.0.32",
        "volumes.kubernetes.io/controller-managed-attach-detach": "true"
    },
    "operatingSystem": "linux 4.10.0-28-generic",
    "operatingSystemImage": "Ubuntu 16.04.3 LTS",
    "dockerVersion": "docker://18.6.1",
    **"cpu": "32",
    "cpuUsedRatio": "0.00",
    "memory": "131983120Ki",
    "memoryUsedRatio": "0.08",
    "storage": "731301344Ki",
    "storageUsedRatio": "10.00",
    "podCount": 110,
    "podUsedRatio": "0.00"**
}

expect data
![qq20190308-113528](https://user-images.githubusercontent.com/47511655/54005971-6e1ffa00-4196-11e9-9adb-fa0ddf9997a3.png)

**Comment by thesinglecloud** [comment]
fixed in deployment branch, these values should be fetched from metrics

**Comment by tanxu-zdns** [comment]
fixed
