### ISSUE TITLE
error returns when creating daemonset with specific config

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#207]
POST http://10.0.0.30:30000/apis/zcloud.cn/v1/clusters/chengdu/namespaces/default/daemonsets
with
{"containers":[{"name":"dnsserver","exposedPorts":[{"protocol":"udp","name":"diekeulec","port":53}],"image":"diekeulect/dnsserver","env":[{"name":"fdsffgg","value":"ujhgfddfgds"},{"name":"dgdsgdfg","value":"hregeggr"}],"volumes":[{"type":"configmap","name":"dsnbfjham","mountPath":"/hgfds"},{"type":"secret","name":"dfgdgdgdgdgdgdsgdfgsdfgsdfgds","mountPath":"/hgfdsa"},{"type":"persistentVolume","name":"sdfasfas","mountPath":"/fghkjdfsf"},{"type":"persistentVolume","name":"ggrewt4","mountPath":"/sfdighjn"}]},{"name":"diekeulec","image":"nginx","exposedPorts":[{"protocol":"tcp","name":"sfsfsf","port":80}],"env":[{"name":"sdhgfdsa","value":"yutrgefvf"}],"volumes":[{"type":"configmap","name":"fgytrfsdcvbgh","mountPath":"/jhgfd"},{"type":"secret","name":"fdgsfgnh","mountPath":"/ytgfds"},{"type":"persistentVolume","name":"sdfasfas","mountPath":"/kjhgfdg"},{"type":"persistentVolume","name":"ggrewt4","mountPath":"/uytgfgfd"}]}],"persistentVolumes":[{"name":"sdfasfas","size":"7Gi","storageClassName":"cephfs"},{"name":"ggrewt4","size":"8Gi","storageClassName":"lvm"}],"advancedOptions":{"reloadWhenConfigChange":true,"exposedMetric":{"path":"/hgfdfsd","port":8989}},"name":"daemon"}

returns
{"code":"ConnectClusterFailed","status":422,"type":"error","message":"create daemonSet failed DaemonSet.apps \"daemon\" is invalid: [spec.template.spec.volumes[4].name: Duplicate value: \"vol0\", spec.template.spec.volumes[5].name: Duplicate value: \"vol1\", spec.template.spec.volumes[6].name: Duplicate value: \"sdfasfas\", spec.template.spec.volumes[7].name: Duplicate value: \"ggrewt4\"]"}

**Comment by zdnsjoe** [comment]
fix on issue207

**Comment by tanxu-zdns** [comment]
{"code":"ConnectClusterFailed","status":422,"type":"error","message":"create daemonSet failed DaemonSet.apps \"ywehrjnfmds\" is invalid: [spec.template.spec.volumes[6].name: Duplicate value: \"lvmsfswef\", spec.template.spec.volumes[7].name: Duplicate value: \"cephsdfsafe\"]"}
