### ISSUE TITLE
The first rollback version of deployment will display as blank

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#215]
![image](https://user-images.githubusercontent.com/47511655/63668917-18561180-c80b-11e9-9607-e6a32ed02b1c.png)

**Comment by jlccwss** [comment]
回滚时显示两个属性，1、版本号，2、版本说明，通过选择版本号显示对应的版本说明（更新原因字段）。第一个版本为初次安装，更新说明为空逻辑上是OK的。对于deployment回滚后产生空的更新原因版本，需要ben做深入调研。
