### ISSUE TITLE
取消创建集群，有可能会导致该集群update永远失败

### ISSUE THREAD

**Issue by hiwyw** [zdnscloud/singlecloud#220]

**Comment by hiwyw** [comment]
复现方法：
1.在controlplane节点执行：watch -n 1 'docker rm -f kube-apiserver'
2.通过ui创建集群
3.查看集群日志可以发现集群创建会反复检查apiserver健康状态
4.终止安装
5.更新集群

**Comment by tanxu-zdns** [comment]
has fixed
