### ISSUE TITLE
storage list page is not refreshed after creating storage

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#223]
![image](https://user-images.githubusercontent.com/47511655/63902928-42434a00-ca3e-11e9-991d-a07d20fa85fb.png)

**Comment by jlccwss** [comment]
所有带有新建功能的列表页，都应该有刷新功能，就像集群列表页面那样的刷新

**Comment by jlccwss** [comment]
自动刷新

**Comment by gsmlg** [comment]
add refresh on storage page
