### ISSUE TITLE
“用户编辑”功能现在没有作用, 应该隐藏起来

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#227]
@jlccwss 你看一下这个是保留还是隐藏

![image](https://user-images.githubusercontent.com/47511655/63989851-6f622c00-cb14-11e9-8895-3601ca4fd302.png)

**Comment by jlccwss** [comment]
不用隐藏。这个功能很快就会加内容，一个帐号不可能没有其他的属性。所以就没有必要改来改去的了。

**Comment by tanxu-zdns** [comment]
ok
