### ISSUE TITLE
当登录的是一个普通用户时, 导航栏的部分功能需要被隐藏

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#228]
@jlccwss 少帅看一下哪些功能菜单需要隐藏

![image](https://user-images.githubusercontent.com/47511655/63990107-5017ce80-cb15-11e9-8531-2660e436302e.png)

**Comment by jlccwss** [comment]
权限问题放到下个版本做，下周一讨论具体权限的功能。

**Comment by tanxu-zdns** [comment]
![image](https://user-images.githubusercontent.com/47511655/67080077-08cdc600-f1c7-11e9-849a-2da0ea5c8cb0.png)

**Comment by tanxu-zdns** [comment]
还得加上 监控中心
