### ISSUE TITLE
某些功能项在 导航栏 和 列表页 的名字不一致

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#231]
1. 服务入口
2. udp服务入口

![image](https://user-images.githubusercontent.com/47511655/63996026-03d88880-cb2d-11e9-9919-b4df0efc460f.png)
![image](https://user-images.githubusercontent.com/47511655/63996039-1488fe80-cb2d-11e9-9eb0-63ec62786613.png)

**Comment by jlccwss** [comment]
翻译的问题，我来改
