### ISSUE TITLE
“ driver name cephfs.csi.ceph.com not found ” returns when using ceph storage

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#232]
create a deployment with ceph storage

events:

Warning | FailedMount | MountVolume.MountDevice failed for volume "pvc-57fbabe7-cae9-11e9-8905-44a84224c9a3" : driver name cephfs.csi.ceph.com not found in the list of registered CSI drivers | 16 minutes ago
Warning | FailedMount | MountVolume.MountDevice failed for volume "pvc-57faaec2-cae9-11e9-8905-44a84224c9a3" : driver name cephfs.csi.ceph.com not found in the list of registered CSI drivers | 12 minutes ago
Warning | FailedMount | Unable to mount volumes for pod "hello-7b8689466d-4ptkd_quota-0-0(580035a3-cae9-11e9-8905-44a84224c9a3)": timeout expired waiting for volumes to attach or mount for pod "quota-0-0"/"hello-7b8689466d-4ptkd". list of unmounted volumes=[fasfsceph asfsadfceph]. list of unattached volumes=[dkjklasfj-vol0 dkjklasfj-vol1 dkjklasfj-vol2 dkjklasfj-vol3 safasfelvm sfasfalvm fasfsceph asfsadfceph hgdfs-vol0 hgdfs-vol1 hgdfs-vol2 hgdfs-vol3 asfadf-vol0 asfadf-vol1] | 3 minutes ago

**Comment by tanxu-zdns** [comment]
又遇到这个问题


Warning | FailedScheduling | pod has unbound immediate PersistentVolumeClaims (repeated 8 times) | 7 minutes ago
-- | -- | -- | --
Normal | Scheduled | Successfully assigned default/sfas-7b9b6cf8dd-ls2zr to 10.0.0.136 | 7 minutes ago
Normal | SuccessfulAttachVolume | AttachVolume.Attach succeeded for volume "pvc-dcb4a567-dab4-11e9-8948-52540053eeee" | 7 minutes ago
Normal | SuccessfulAttachVolume | AttachVolume.Attach succeeded for volume "pvc-dcb30211-dab4-11e9-8948-52540053eeee" | 7 minutes ago
Warning | FailedMount | MountVolume.MountDevice failed for volume "pvc-dcb30211-dab4-11e9-8948-52540053eeee" : driver name cephfs.csi.ceph.com not found in the list of registered CSI drivers | a minute ago
Warning | FailedMount | Unable to mount volumes for pod "sfas-7b9b6cf8dd-ls2zr_default(dcbda718-dab4-11e9-8948-52540053eeee)": timeout expired waiting for volumes to attach or mount for pod "default"/"sfas-7b9b6cf8dd-ls2zr". list of unmounted volumes=[wer]. list of unattached volumes=[wer trs default-token-rljtg]

**Comment by yuchunyun** [comment]
lvm/ceph的csi-plugin pod在终止时会删除/var/lib/kubelet/plugins/plugins_registry/目录。如果节点上同时运行两套存储，当有一个存储的csi-plugin重启/删除时就会影响到另外一个存储。
已经在最新版本的singlecloud/storagecluster-del-check更新
