### ISSUE TITLE
storageclass名称问题

### ISSUE THREAD

**Issue by jlccwss** [zdnscloud/singlecloud#234]
创建存储时，storageclass名称应该与存储集群名称一致。workload创建存储模版时，显示存储名称

**Comment by tanxu-zdns** [comment]
![image](https://user-images.githubusercontent.com/47511655/64941047-35c14d00-d898-11e9-993e-d219dc35f229.png)

![image](https://user-images.githubusercontent.com/47511655/64941037-2b06b800-d898-11e9-9947-3d3a2f78e0ce.png)

名称改了之后, 参数和后端对应不上
