### ISSUE TITLE
keep refreshing pages will cause "undefined" requests

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#235]
1. keep refresh the pages
such as:
节点列表, 节点详情
pod IP , 服务IP
应用商店, 应用管理
2. observe the requests

the following occurs:
the requestes became undefined.

**Comment by tanxu-zdns** [comment]
如果不能重现, 可以多刷新几次

**Comment by tanxu-zdns** [comment]
![image](https://user-images.githubusercontent.com/47511655/64005278-a3ecdc80-cb42-11e9-86a4-86540636f3b1.png)
![image](https://user-images.githubusercontent.com/47511655/64005291-abac8100-cb42-11e9-9c7f-9d2dcad56196.png)
![image](https://user-images.githubusercontent.com/47511655/64005304-b109cb80-cb42-11e9-9d8d-c6b0202a97a6.png)

![image](https://user-images.githubusercontent.com/47511655/64005298-aea77180-cb42-11e9-873c-261c5e5cf646.png)
![image](https://user-images.githubusercontent.com/47511655/64005310-b49d5280-cb42-11e9-9bcb-90527e7f9935.png)

**Comment by tanxu-zdns** [comment]
在master分支

节点详情
应用商店 
应用管理
POD IP , 服务IP 

页面还存在undefined的问题
@gsmlg

**Comment by gsmlg** [comment]
当前修改只在：  storagecluster-del-check

**Comment by tanxu-zdns** [comment]
在 storagecluster-del-check 分支也发现

节点详情
应用商店
应用管理
POD IP , 服务IP

页面还存在undefined的问题
@gsmlg

**Comment by gsmlg** [comment]
重构了所有数据加载逻辑
