### ISSUE TITLE
pod ip 如果是主机IP, 在pod ip页面无法显示

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#250]
但是统计ip个数的时候是统计了主机ip的

![image](https://user-images.githubusercontent.com/47511655/64223572-15dc7180-cf07-11e9-93e0-12487651d733.png)

**Comment by jlccwss** [comment]
如果k8s的POD IP段或是svc IP段与主机IP段重复，则不允许创建

**Comment by hiwyw** [comment]
that because prometheus-node-exporter will use hostNetwork，suggest do not display these ips if not in podCIDR
