### ISSUE TITLE
创建完UDP的svc后，弹窗确定跳转页面应该是UDP服务入口新建页面，而不是服务入口新建页面

### ISSUE THREAD

**Issue by jlccwss** [zdnscloud/singlecloud#259]

**Comment by tanxu-zdns** [comment]
@jlccwss 
如果创建的svc同时具有tcp和udp端口应该怎么办

![image](https://user-images.githubusercontent.com/47511655/64323092-5c5cc980-cff6-11e9-9550-55cea0aff42e.png)

**Comment by gsmlg** [comment]
根据第一个配置的端口的协议来跳转到ingress/udpingress

**Comment by tanxu-zdns** [comment]
跳转到udpingress 的时候没有选中对应的service
![image](https://user-images.githubusercontent.com/47511655/64577954-8b858900-d3b0-11e9-967f-bcde7540eeea.png)
