### ISSUE TITLE
当删除使用中的存储时, 前端需要报错

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#263]
分支: storagecluster-del-check

1. 创建一个deployment并添加ceph和lvm存储,
2. 在集群管理-存储页面删除ceph和lvm存储,

结果:
删除时后端报错, 但是前端没有报错.

![image](https://user-images.githubusercontent.com/47511655/64943017-2b558200-d89d-11e9-8981-6b2e380e111a.png)

**Comment by gsmlg** [comment]
当前所有删除操作都是按照异步来处理的，前端无法报错

**Comment by gsmlg** [comment]
storagecluster-del-check
