### ISSUE TITLE
升级deplyment后, 副本状态的总个数会超出上限.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#266]
1. 创建一个workload包含10个副本,
2. 创建完成后升级workload,
3. 观察状态中的总个数,

结果:
总个数超出上限.
上限为10, 这里为13.

**Comment by tanxu-zdns** [comment]
网络有点问题, 上传图片失败, 稍后在上传.

**Comment by tanxu-zdns** [comment]
分支: add-workload-status

**Comment by zdnsjoe** [comment]
kubectl get deploy -n default sajflds -o json

"status": {
        "availableReplicas": 8,
        "observedGeneration": 3,
        "readyReplicas": 8,
        "replicas": 13,
        "unavailableReplicas": 5,
        "updatedReplicas": 5
    }

update will kill old pod  after create new pod succeed, the field Replicas description as below:
// Total number of non-terminated pods targeted by this deployment (their labels match the selector)

**Comment by zdnsjoe** [comment]
the same to issue 267
