### ISSUE TITLE
statefulset中状态总数在创建过程中少于副本数

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#267]
1. 创建一个具有10个副本的statefulset,
2. 观察创建过程,

结果:
创建过程中, 总数不正确.

![image](https://user-images.githubusercontent.com/47511655/65016667-6f0cc200-d957-11e9-804c-85039ece175d.png)

**Comment by tanxu-zdns** [comment]
分支: add-workload-status

**Comment by zdnsjoe** [comment]
@gsmlg 

deployment  statefulset status should be： status.ReadyReplicas/spec.Replicas
