### ISSUE TITLE
为statefulset进行升级操作后, 状态中的成功个数不正确.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#268]
分支: add-workload-status
1. 创建一个具有10个副本的statefulset (e.g. nginx),
2. 给statefulset进行升级(e.g. nginx:stable),

结果:
升级过程中会导致状态在 “9/10” 和 “10/10” 来回切换.
当升级成功后, 状态会停止切换.

![image](https://user-images.githubusercontent.com/47511655/65017203-b5165580-d958-11e9-8f4b-0b2d6a5582f2.png)
![image](https://user-images.githubusercontent.com/47511655/65017250-d8410500-d958-11e9-9d15-cc60f347cd1c.png)

**Comment by tanxu-zdns** [comment]
daemonset 有同样的问题.

**Comment by zdnsjoe** [comment]
it is normal case， update will complete one by one, so it will switch between 9/10 and 10/10
