### ISSUE TITLE
安装镜像仓库时, storagesize没有存储单位, 而且不能手动输入单位

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#269]
分支: registry-monitor-new
![image](https://user-images.githubusercontent.com/47511655/65110952-bf922700-da0c-11e9-9a42-a2a6889ae6d9.png)

**Comment by cindyqiong** [comment]
前台展示加了单位 只需要填数字即可  后台默认单位就是Gi
