### ISSUE TITLE
更新集群之后, 没有跳转到集群列表页面.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#279]
分支: master

1. 创建一个健康的集群, 
2. 删除一个节点并保存,

结果:
停留在集群配置界面.

期望结果:
跳转到集群列表页面.

![image](https://user-images.githubusercontent.com/47511655/65401319-eaf48780-ddf9-11e9-9e79-1ab2df2d13f5.png)

**Comment by gsmlg** [comment]
master 上已修复
