### ISSUE TITLE
集群安装成功后, 节点数量显示为0.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#284]
![image](https://user-images.githubusercontent.com/47511655/66371271-54b58980-e9d5-11e9-8065-9036c055c27a.png)

**Comment by gsmlg** [comment]
节点数量是nodeCount，当时nodeCount为0

**Comment by tanxu-zdns** [comment]
@hiwyw 请看一下这个问题

**Comment by hiwyw** [comment]
原因：nodeCount的获取方式为singlecloud向集群kube-apiserver get nodes得到，有可能存在集群刚创建完成，向apiserver的get nodes请求失败，nodeCount默认为0

**Comment by hiwyw** [comment]
可选的修复方案：1.在获取集群状态及统计信息的过程中，任何与kube-apiserver的请求发生错误都将集群状态置为unreachable（此状态下nodeCount依旧为0） 2.集群的nodeCount获取方式为显示集群配置中的节点数量
