### ISSUE TITLE
在deployment/statefulset详情页面, 多次点击副本增加/减少按钮后, 部分点击不会生效.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#286]
比如点击加号10次, 可能只增加了2两个副本.

![image](https://user-images.githubusercontent.com/47511655/66372899-d1e2fd80-e9d9-11e9-8222-4e576dd399d6.png)

**Comment by tanxu-zdns** [comment]
@gsmlg 请看一下

**Comment by gsmlg** [comment]
当前是只有在后端接受增加了之后才会再次增加replicas的数量

**Comment by gsmlg** [comment]
现在根据后端返回数据更新
