### ISSUE TITLE
创建集群时, 在转发dns填入数据, 然后删除数据, 会传入null到后端.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#291]
1. 在转发dns1填入“abcde”, dns2填入“abcd”,
2. 删除dns1和dns2,
3. 点击下方的保存按钮,

结果:
传入null到后端.

期望结果:
不传值到后端.

![image](https://user-images.githubusercontent.com/47511655/66532914-b3991100-eb43-11e9-9d73-3326b9b63c7a.png)

**Comment by gsmlg** [comment]
如果用户touch到对话框，就应该会有输入值

**Comment by tanxu-zdns** [comment]
@jlccwss 少帅看一下

**Comment by tanxu-zdns** [comment]
后端进行了处理
