### ISSUE TITLE
创建redis app时如果修改了masterport, 会导致redis-slave probe失败, 然后crashloopbackoff.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#309]
Events:
  Type     Reason     Age                    From                 Message
  ----     ------     ----                   ----                 -------
  Warning  Unhealthy  29m (x40 over 64m)     kubelet, 10.0.0.139  Readiness probe failed: Could not connect to Redis at 127.0.0.1:6379: Connection refused
  Warning  BackOff    9m38s (x200 over 63m)  kubelet, 10.0.0.139  Back-off restarting failed container
  Normal   Pulled     4m47s (x18 over 64m)   kubelet, 10.0.0.139  Successfully pulled image "bitnami/redis:4.0.9"

**Comment by zdnsjoe** [comment]
will remove redis port config

**Comment by tanxu-zdns** [comment]
需要在master上修改
