### ISSUE TITLE
当暂停或者驱逐一个存储节点时, 前端未报错.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#348]
![image](https://user-images.githubusercontent.com/47511655/70218258-a2eccc00-177d-11ea-8517-311f32ac1f58.png)

**Comment by cindyqiong** [comment]
![image](https://user-images.githubusercontent.com/16930554/74206656-4810ad00-4cb7-11ea-8f86-ffdcc6572e8e.png)
前端已处理
