### ISSUE TITLE
终止集群的创建操作时, 前端没有向后台发起终止操作.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#351]
分支: service-mesh

![image](https://user-images.githubusercontent.com/47511655/71341812-df9a2f00-2595-11ea-9df8-75986e622a38.png)

**Comment by cindyqiong** [comment]
![image](https://user-images.githubusercontent.com/16930554/75405589-13eceb80-5949-11ea-8bd3-5af3150a50c7.png)
现在，最新的master 无法复现这个bug

**Comment by tanxu-zdns** [comment]
无法复现, 关闭
