### ISSUE TITLE
在tap功能中, 如果流量过大, 页面会有较强的卡顿, cpu会占用过高.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#362]
![image](https://user-images.githubusercontent.com/47511655/71810713-f9fffc80-30ad-11ea-9935-eadb49dba126.png)

**Comment by tanxu-zdns** [comment]
![image](https://user-images.githubusercontent.com/47511655/71810850-49dec380-30ae-11ea-8e4f-a168eec330a9.png)

**Comment by gsmlg** [comment]
对速度做了限制
