### ISSUE TITLE
在tap功能中, Latency数据计算有误.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#364]
![image](https://user-images.githubusercontent.com/47511655/71863897-46dce500-3139-11ea-894d-2895804efde6.png)
linkerd中
![image](https://user-images.githubusercontent.com/47511655/71863918-53f9d400-3139-11ea-82d0-918cbdca3c2d.png)

**Comment by gsmlg** [comment]
计算错误，已修复
