### ISSUE TITLE
在workload-update-cnt功能中, daemonset没有用颜色区别进度.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#366]
![image](https://user-images.githubusercontent.com/47511655/72034087-031be400-32cf-11ea-9642-1f0b17256943.png)

**Comment by tanxu-pro** [comment]
daemonset中的个数显示现在正确, 颜色还没有修改

现在的颜色
![image](https://user-images.githubusercontent.com/50820756/73640256-e5ad2080-46a8-11ea-9401-63140395ef3c.png)

deployment 中的颜色
![image](https://user-images.githubusercontent.com/50820756/73640375-168d5580-46a9-11ea-9838-5b8eb7b6bd86.png)
