### ISSUE TITLE
app处于创建中或者删除中状态时, 前端没有显示app的名称.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#397]
![image](https://user-images.githubusercontent.com/47511655/75884045-11195b80-5e5f-11ea-8453-cd5e18a97659.png)

**Comment by tanxu-zdns** [comment]
已经可以显示名称, 但是删除时的 删除线 丢失.
![image](https://user-images.githubusercontent.com/47511655/77382124-77d4c980-6dba-11ea-99c2-aa69f6818d0c.png)

**Comment by cindyqiong** [comment]
现在展现的逻辑是：1. 只要出现了删除时间 就是有下划线的   2.状态是成功并且无删除时间的情况下 是成功样式可点击的  3. 其他情况  均为普通不可点击样式
