### ISSUE TITLE
删除使用中的nfs存储, 没有报错 (ceph lvm会报错: 使用中, 无法删除.).

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#412]
![image](https://user-images.githubusercontent.com/47511655/77025232-817dbc00-69cb-11ea-92ef-ae5a4ca6770d.png)

**Comment by yuchunyun** [comment]
@jlccwss     nfs存储的csi咱们没有开发，直接用的k8s官方的provisioner，它实际上就做了一件事，用户申请pvc的时候，在pvc里写死nfs的信息。这样申请完nfs类型的pvc后，这个provisioner  就没有任何作用了，可以删除，也不影响pvc的使用。你看看要不要限制用户不允许删除呢？

**Comment by jlccwss** [comment]
所有存储统一逻辑处理，有pod使用不允许删除
