### ISSUE TITLE
更新iscsi存储时, 如果其中一个target不填, 会传入空字符串到后端.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#416]
![image](https://user-images.githubusercontent.com/47511655/77277051-17308880-6cf7-11ea-93a0-07844bd7ca96.png)

**Comment by gsmlg** [comment]
@tanxu-zdns 
这不是bug，都是已用户输入为准的

**Comment by tanxu-zdns** [comment]
ok, 少帅说会改设计, 先关闭了
