### ISSUE TITLE
nfs pvc size won't be returned when the nfs pvc size less than 1G

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#50]
pvc-2781af8a-70a9-11e9-9f97-44a84224c9a3 and pvc-4163b1fa-70ad-11e9-9f97-44a84224c9a3 are less than 1G

{
            "creationTimestamp": null,
            "name": "nfs",
            "size": 100,
            "freesize": 100,
            "pvs": [
                {
                    "name": "pvc-2781af8a-70a9-11e9-9f97-44a84224c9a3",
                    "pods": [
                        {
                            "name": "ng2-0"
                        }
                    ]
                },
                {
                    "name": "pvc-03eefd8c-70ad-11e9-9f97-44a84224c9a3",
                    "size": 2,
                    "pods": [
                        {
                            "name": "ng3-0"
                        },
                        {
                            "name": "ng4-0"
                        }
                    ]
                },
                {
                    "name": "pvc-4163b1fa-70ad-11e9-9f97-44a84224c9a3",
                    "pods": [
                        {
                            "name": "ng5-0"
                        }
                    ]
                }
            ]
        }

**Comment by yuchunyun** [comment]
fixd
