### ISSUE TITLE
"self" of the "links" in the storageclass should be removed

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#59]
{
    "type": "collection",
    "resourceType": "storageclass",
    "links": {
        "self": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses"
    },
    "data": [
        {
            "id": "lvm",
            "type": "storageclass",
            "links": {
                "collection": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses",
                "self": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses/lvm"
            },
            "creationTimestamp": "2019-05-07T07:18:57Z",
            "name": "lvm"
        },
        {
            "id": "nfs",
            "type": "storageclass",
            "links": {
                "collection": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses",
                "self": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses/nfs"
            },
            "creationTimestamp": "2019-05-07T07:19:02Z",
            "name": "nfs"
        }
    ]
}

"self": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses/nfs"
"self": "http://10.0.0.33:30000/apis/zcloud.cn/v1/clusters/chengdu/storageclasses/lvm"
should be removed, because singlecloud don't suppot resource method "GET"

**Comment by zdnsjoe** [comment]
fixed

**Comment by tanxu-zdns** [comment]
fixed
