### ISSUE TITLE
error returns if don't choose storage node when creating cluster.yml

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#68]
[+] Is host (10.0.0.101) an Storage host (y/n)? [n]: n
[+] Is host (10.0.0.102) an Storage host (y/n)? [n]: n
[+] Is host (10.0.0.103) an Storage host (y/n)? [n]: n

finally:
FATA[0179] None available lvm storge!
and no config file generated.

**Comment by hiwyw** [comment]
It has beed fixed(zke commit 9cac64cf205535eaae38f84ebf927b69132bdf44),can close this issue
