### ISSUE TITLE
creating storage success when creating deployment with errors

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#81]
creating deployment with storage

{
    "name": "deployment-test",
    "replicas": 2,
    "containers": [
        {
            "name": "deployment-test",
            "image": "nginx:stable",
            "command": [
                "sleep"
            ],
            "args": [
                "3600"
            ],
            "exposedPorts": [
                {
                    "name": "deployment-test",
                    "port": 2,
                    "protocol": "tcp"
                }
            ],
            "env": [
                {
                    "name": "deployment-test",
                    "value": "deployment-testdcivepbf"
                }
            ],
            "volumes": [
                {
                    "type": "configmap",
                    "name": "configmap-test",
                    "mountPath": "/deployment-testsoluyuacAEhWuOqO"
                },                {
                    "type": "secret",
                    "name": "secret-test",
                    "mountPath": "/deployment-testsoluyuacAEhWuOqO"
                }
            ]
        }
    ],
    "advancedOptions": {
        "relaodWhenConfigChange": true,
        "exposedServiceType": "clusterip",
        "exposedServices": [
            {
                "containerPortName": "deployment-testjzxgsrbe",
                "servicePort": 2,
                "autoCreateIngress": true,
                "ingressHost": "deployment-testnflmjstt",
                "ingressPath": "/deployment-testwetcbmlgAeGsSMzv",
                "ingressProtocol": "http"            }
        ],
        "exposedMetric": {
            "path": "/deployment-testqoonfdagtulnyWei",
            "port": 2
        }
    },
    "volumeClaimTemplates": [
        {
            "name": "deployment-test4",
            "size": "1",
            "storageClassName": "nfs"
        }
    ]
}

return
{
    "code": "ConnectClusterFailed",
    "status": 422,
    "type": "error",
    "message": "create deploy failed Deployment.apps \"deployment-test\" is invalid: spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: \"/deployment-testsoluyuacAEhWuOqO\": must be unique"
}

but the storage "deployment-test4" created successfully.

expected behavior:
storage shouldn't create succesfully if creating deployment with error.

**Comment by tanxu-zdns** [comment]
fixed

**Comment by tanxu-zdns** [comment]
encountered again, reopen it

**Comment by zdnsjoe** [comment]
fixed

**Comment by tanxu-zdns** [comment]
fixed
