### ISSUE TITLE
duplicate "overall" guide on the top-left page.

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#95]
![duplicate_overall](https://user-images.githubusercontent.com/47511655/59261032-4e094680-8c6f-11e9-87ff-33512404658e.png)

**Comment by jlccwss** [comment]
这个不是重复，设计的时候上面代表用户操作的区域。并且想让用户可以快速切换集群，但是如果用户没有集群的话，操作区域只有总览，所以上面也就有了一个总览。

**Comment by tanxu-zdns** [comment]
ok
