### ISSUE TITLE
no secret listed when choosing the storage as secret in deployment creating page

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#97]
1. create a namespace named namespace-test,
2. create a secret named secret-test in namespace-test,
3. mount the storage type as secret,
4. try to find secret-test,

the following occurs:
not found secret-test, no secret listed.

![secretnolink](https://user-images.githubusercontent.com/47511655/59330227-7c485e00-8d23-11e9-9e66-36051ff8b4a7.png)

**Comment by gsmlg** [comment]
@tanxu-zdns 
fixed
