### ISSUE TITLE
the removed ports send to backend when creating deployment

### ISSUE THREAD

**Issue by tanxu-zdns** [zdnscloud/singlecloud#99]
1. go to deployment creating page,
2. add a port named sdfsdff
4. switch on the advanced option,
5. click the service check box,
6. remove the port in the pod,
7. create this deployment,

the following occurs:
creating failed, retrun "{"code":"InvalidOption","status":422,"type":"error","message":"unknown container port with name:sdfsdff"}"

note:
parameter send to backend contains the removed port.

**Comment by tanxu-zdns** [comment]
@cindyqiong this issue still present

**Comment by gsmlg** [comment]
@cindyqiong 
Check is issus

**Comment by tanxu-zdns** [comment]
issue should be closed, new version don't support this function
